name: E2E Tests

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-e2e-tests]

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - id: set
        run: |
          VERSIONS='["1.8.8", "1.16.5", "1.21.5"]'
          echo "matrix=$VERSIONS"
          echo "::set-output name=matrix::{\"version\": $VERSIONS}"

  run-tests:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(needs.set-matrix.outputs.matrix).version }}
    env:
      VERSION: ${{ matrix.version }}
    steps:
      - name: Copy repo files to host
        uses: actions/checkout@v4

      - name: Download latest LPC-Pro
        uses: dawidd6/action-download-artifact@v11
        with:
          github_token: ${{ secrets.LPCPRO_E2E_REPO_PAT }}
          name: lpcpro-jar
          repo: wikmor/lpcpro
          workflow: build.yml
          path: ./plugins

      - name: Debug plugins on host
        run: ls -lh ./plugins

      - name: Download Paper
        run: ./scripts/download-paper.sh "$VERSION"

      - name: Start Paper
        run: |
          docker compose up -d paper_${VERSION//./_}
          ./scripts/wait-for-server.sh servers/${VERSION}/logs/latest.log

      - name: Run tests
        run: docker compose run --rm test_${VERSION//./_}
