name: E2E Tests

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-e2e-tests]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: 1.16.5
            version_underscore: 1_16_5
          - version: 1.21.5
            version_underscore: 1_21_5

    env:
      VERSION: ${{ matrix.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Download LPC-Pro JAR artifact from private repo
        uses: dawidd6/action-download-artifact@v11
        with:
          github_token: ${{ secrets.LPCPRO_E2E_REPO_PAT }}
          workflow: build.yml
          name: lpcpro-jar
          path: ./plugins
          repo: wikmor/lpcpro

      - name: List plugin jar
        run: ls -lh plugins/

      - name: Build server image
        run: docker compose build paper_${{ matrix.version_underscore }}
      
      - name: Start server
        run: docker compose up -d paper_${{ matrix.version_underscore }}

      - name: Wait for server log
        run: ./scripts/wait-for-server.sh servers/${{ matrix.version }}/logs/latest.log
      
      - name: Run tests
        run: docker compose run --rm test_${{ matrix.version_underscore }}
      
      - name: Stop server
        run: docker compose stop paper_${{ matrix.version_underscore }}
