name: E2E Tests

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-e2e-tests]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download LPC-Pro JAR artifact from private repo
        uses: actions/download-artifact@v4
        with:
          name: lpcpro-jar
          path: ./plugins
          github-token: ${{ secrets.LPCPRO_E2E_REPO_PAT }}
          repository: wikmor/lpcpro

      - name: List plugin jar
        run: ls -lh plugins/
