name: E2E Tests

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-e2e-tests]

jobs:
  test_1_16_5:
    name: Test Paper 1.16.5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download plugin
        uses: dawidd6/action-download-artifact@v11
        with:
          github_token: ${{ secrets.LPCPRO_E2E_REPO_PAT }}
          workflow: build.yml
          name: lpcpro-jar
          path: ./plugins
          repo: wikmor/lpcpro

      - name: Start server & wait
        run: |
          docker compose up -d paper_1_16_5
          ./scripts/wait-for-server.sh servers/1.16.5/logs/latest.log

      - name: Run tests
        run: docker compose run --rm test_1_16_5

  test_1_21_5:
    name: Test Paper 1.21.5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download plugin
        uses: dawidd6/action-download-artifact@v11
        with:
          github_token: ${{ secrets.LPCPRO_E2E_REPO_PAT }}
          workflow: build.yml
          name: lpcpro-jar
          path: ./plugins
          repo: wikmor/lpcpro

      - name: Start server & wait
        run: |
          docker compose up -d paper_1_21_5
          ./scripts/wait-for-server.sh servers/1.21.5/logs/latest.log

      - name: Run tests
        run: docker compose run --rm test_1_21_5
