name: E2E Tests

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-e2e-tests]

env:
  DEFAULT_VERSIONS: |
    1.8.8
    1.16.5
    1.21.4
    1.21.5
    1.21.8

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - id: set
        run: |
          matrix=$(jq -c -n --arg versions "$DEFAULT_VERSIONS" '
            def versions: ($versions | split("\n") | map(. | gsub(","; "") | gsub(" "; "") | select(length > 0)));
            def engines: ["paper", "spigot"];
            [
              versions[] as $v |
              engines[] as $e |
              {version: $v, engine: $e}
            ]
          ')
          echo "matrix={\"include\":$matrix}" >> "$GITHUB_OUTPUT"

  run-tests:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.set-matrix.outputs.matrix).include }}
    env:
      VERSION: ${{ matrix.version }}
      ENGINE: ${{ matrix.engine }}
    steps:
      - name: Copy repo files to host
        uses: actions/checkout@v4

      - name: Download latest LPC-Pro plugin
        uses: dawidd6/action-download-artifact@v11
        with:
          github_token: ${{ secrets.LPCPRO_E2E_REPO_PAT }}
          name: lpcpro-jar
          repo: wikmor/lpcpro
          workflow: build.yml
          path: ./plugins

      - name: Download softdependency plugins
        run: ./scripts/download-plugins.sh

      - name: Download server jar
        run: |
          mkdir -p ./server-jars/${ENGINE}
          if [[ "$ENGINE" == "paper" ]]; then
            ./scripts/download-paper.sh "$VERSION"
            mv "./paper/$VERSION/paper-$VERSION.jar" "./server-jars/$ENGINE/$VERSION.jar"
          else
            URL="https://github.com/wikmor/lpcpro-e2e/releases/download/spigot-$VERSION/spigot-$VERSION.jar"
            echo "Checking if Spigot jar exists: $URL"
            if curl --head --fail --silent "$URL" > /dev/null; then
              curl -sLo "./server-jars/$ENGINE/$VERSION.jar" "$URL"
            else
              echo "❌ Spigot $VERSION jar not found in releases!"
              exit 1
            fi
          fi

      - name: Generate Docker Compose file
        run: ./scripts/gen-compose.sh "$VERSION" "$ENGINE" > docker-compose.yml

      - name: Start server
        run: |
          docker compose up -d ${ENGINE}_${VERSION//./_}
          ./scripts/wait-for-server.sh servers/${VERSION}/logs/latest.log

      - name: Show logs
        run: cat servers/${VERSION}/logs/latest.log || echo "Log not found"

      - name: Run tests
        run: docker compose run --rm --no-deps test_${VERSION//./_}
