name: E2E Tests

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-e2e-tests]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download LPC-Pro JAR artifact from private repo
        uses: dawidd6/action-download-artifact@v11
        with:
          github_token: ${{ secrets.LPCPRO_E2E_REPO_PAT }}
          workflow: build.yml
          name: lpcpro-jar
          path: ./plugins
          repo: wikmor/lpcpro

      - name: List plugin jar
        run: ls -lh plugins/
